object frmSettingsWnd: TfrmSettingsWnd
  Left = 0
  Top = 0
  Caption = 'frmSettingsWnd'
  ClientHeight = 233
  ClientWidth = 525
  Color = clWindow
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  OldCreateOrder = False
  PixelsPerInch = 96
  TextHeight = 13
  object pnlGlass: TPanel
    Left = 0
    Top = 0
    Width = 525
    Height = 39
    Align = alTop
    AutoSize = True
    BevelOuter = bvNone
    TabOrder = 0
    object sceGlassOptions: TSharpEColorEditorEx
      AlignWithMargins = True
      Left = 8
      Top = 0
      Width = 509
      Height = 31
      Margins.Left = 8
      Margins.Top = 0
      Margins.Right = 8
      Margins.Bottom = 8
      VertScrollBar.Smooth = True
      VertScrollBar.Tracking = True
      Align = alTop
      AutoSize = True
      BevelInner = bvNone
      BevelOuter = bvNone
      BorderStyle = bsNone
      Color = clBlack
      ParentColor = False
      TabOrder = 0
      Items = <>
      SwatchManager = SharpESwatchManager1
      OnUiChange = sceGlassOptionsUiChange
      OnExpandCollapse = sceGlassOptionsExpandCollapse
      BorderColor = clBlack
      BackgroundColor = clBlack
      BackgroundTextColor = clBlack
      ContainerColor = clBlack
      ContainerTextColor = clBlack
      ExplicitHeight = 319
    end
  end
  object SharpESwatchManager1: TSharpESwatchManager
    Swatches = <>
    PopulateThemeColors = True
    Width = 100
    ShowCaptions = True
    SwatchHeight = 16
    SwatchWidth = 16
    SwatchSpacing = 4
    SwatchFont.Charset = DEFAULT_CHARSET
    SwatchFont.Color = clWindowText
    SwatchFont.Height = -11
    SwatchFont.Name = 'Tahoma'
    SwatchFont.Style = []
    SwatchTextBorderColor = 16709617
    SortMode = sortName
    BorderColor = clBlack
    BackgroundColor = clBlack
    BackgroundTextColor = clBlack
    Left = 356
    Top = 132
  end
  object tmrRefresh: TTimer
    Enabled = False
    Interval = 1
    OnTimer = tmrRefreshTimer
    Left = 380
    Top = 220
  end
end
