object Form2: TForm2
  Left = 0
  Top = 0
  Width = 434
  Height = 320
  Caption = 'Form2'
  Color = clWhite
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  OldCreateOrder = False
  PixelsPerInch = 96
  TextHeight = 13
  object SharpERoundPanel1: TSharpERoundPanel
    Left = 80
    Top = 96
    Width = 185
    Height = 41
    BevelOuter = bvNone
    Caption = 'SharpERoundPanel1'
    Color = 33023
    ParentBackground = False
    TabOrder = 0
    DrawMode = srpNoBottomLeft
    RoundValue = 10
    BorderColor = clGreen
    Border = True
    BackgroundColor = clBtnFace
  end
end
